export const interests = [
  "Arts & Culture",
  "Business",
  "Children & Youth",
  "Communication",
  "Community",
  "Computer & Technology",
  "Customer Service",
  "Education",
  "Environment",
  "Food",
  "Healthcare",
  "Legal",
  "Languages",
  "Leadership",
  "Manual Labour",
  "Reading & Writing",
  "Recreation",
  "Research",
  "Seniors",
];
