export const interests = [
  "teamwork",
  "problem solving",
  "creativity",
  "negotiation",
  "construction",
  "customer service",
  "communications",
  "creativity",
  "building & construction",
  "human services",
  "legal & advocacy",
  "leadership",
  "listening",
];
