const argon = require("argon2");

exports.seed = async function (knex) {
  // Deletes ALL existing entries
  return knex("jobs")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("jobs").insert([
        {
          posting_id: 1,
          start_time: "9:00 am",
          end_time: "11:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 1,
          start_time: "10:00 am",
          end_time: "1:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 1,
          start_time: "1:00 pm",
          end_time: "4:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 1,
          start_time: "4:00 pm",
          end_time: "9:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 2,
          start_time: "5:00 pm",
          end_time: "9:00 pm",
          openings: 5,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 3,
          start_time: "9:00 am",
          end_time: "3:00 pm",
          openings: 7,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 4,
          start_time: "10:00 am",
          end_time: "1:00 pm",
          openings: 4,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 5,
          start_time: "9:00 am",
          end_time: "12:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 5,
          start_time: "12:00 pm",
          end_time: "2:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 5,
          start_time: "2:00 pm",
          end_time: "5:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 6,
          start_time: "12:00 pm",
          end_time: "4:00 pm",
          openings: 2,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 6,
          start_time: "12:00 pm",
          end_time: "6:00 pm",
          openings: 2,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 7,
          start_time: "12:00 pm",
          end_time: "4:00 pm",
          openings: 2,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 7,
          start_time: "12:00 pm",
          end_time: "6:00 pm",
          openings: 2,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 8,
          start_time: "12:00 pm",
          end_time: "2:00 pm",
          openings: 8,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 9,
          start_time: "9:00 am",
          end_time: "3:00 pm",
          openings: 8,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 10,
          start_time: "7:00 am",
          end_time: "10:00 am",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 10,
          start_time: "10:00 am",
          end_time: "1:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 10,
          start_time: "1:00 pm",
          end_time: "4:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 11,
          start_time: "9:00 am",
          end_time: "2:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 12,
          start_time: "9:00 am",
          end_time: "4:00 pm",
          openings: 15,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 13,
          start_time: "9:00 am",
          end_time: "4:00 pm",
          openings: 15,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 14,
          start_time: "10:00 am",
          end_time: "12:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 15,
          start_time: "6:00 pm",
          end_time: "8:00 pm",
          openings: 10,
          applicants: 0,
          status: "open",
        },
        //t's jobs
        {
          posting_id: 16,
          start_time: "9:00 am",
          end_time: "3:00 pm",
          openings: 8,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 17,
          start_time: "9:00 am",
          end_time: "12:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 17,
          start_time: "12:00 pm",
          end_time: "4:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 18,
          start_time: "7:00 am",
          end_time: "2:00 pm",
          openings: 14,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 19,
          start_time: "2:00 pm",
          end_time: "5:00 pm",
          openings: 4,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 19,
          start_time: "6:00 pm",
          end_time: "8:00 pm",
          openings: 4,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 20,
          start_time: "8:00 am",
          end_time: "2:00 pm",
          openings: 8,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 21,
          start_time: "12:00 pm",
          end_time: "4:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 22,
          start_time: "9:00 am",
          end_time: "2:00 pm",
          openings: 12,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 23,
          start_time: "9:00 am",
          end_time: "4:00 pm",
          openings: 12,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 24,
          start_time: "3:00 pm",
          end_time: "4:15 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 24,
          start_time: "4:30 pm",
          end_time: "5:45 pm",
          openings: 5,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 25,
          start_time: "8:30 am",
          end_time: "9:30 am",
          openings: 4,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 25,
          start_time: "9:30 am",
          end_time: "10:30 am",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 25,
          start_time: "10:30 am",
          end_time: "11:30 am",
          openings: 2,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 26,
          start_time: "4:00 pm",
          end_time: "4:30 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 27,
          start_time: "9:00 am",
          end_time: "12:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 28,
          start_time: "3:00 pm",
          end_time: "7:30 pm",
          openings: 10,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 29,
          start_time: "12:00 pm",
          end_time: "1:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 29,
          start_time: "1:00 pm",
          end_time: "2:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 30,
          start_time: "7:00 pm",
          end_time: "9:00 pm",
          openings: 9,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 30,
          start_time: "9:00 am",
          end_time: "1:00 pm",
          openings: 9,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 31,
          start_time: "6:00 am",
          end_time: "8:00 am",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 31,
          start_time: "10:00 am",
          end_time: "12:00 pm",
          openings: 10,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 32,
          start_time: "12:00 pm",
          end_time: "2:00 pm",
          openings: 15,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 33,
          start_time: "10:00 am",
          end_time: "10:30 am",
          openings: 4,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 33,
          start_time: "10:30 am",
          end_time: "11:00 am",
          openings: 4,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 33,
          start_time: "11:00 am",
          end_time: "11:30 am",
          openings: 4,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 34,
          start_time: "19:00 pm",
          end_time: "23:00 pm",
          openings: 12,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 35,
          start_time: "8:30 am",
          end_time: "9:30 am",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 35,
          start_time: "9:30 am",
          end_time: "10:30 pm",
          openings: 2,
          applicants: 0,
          status: "open",
        },
      ]);
    });
};
