const argon = require("argon2");

exports.seed = async function (knex) {
  // Deletes ALL existing entries
  return knex("jobs")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("jobs").insert([
        {
          posting_id: 1,
          start_time: "9:00 am",
          end_time: "11:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 1,
          start_time: "10:00 am",
          end_time: "1:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 1,
          start_time: "1:00 pm",
          end_time: "4:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 1,
          start_time: "4:00 pm",
          end_time: "9:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 2,
          start_time: "5:00 pm",
          end_time: "9:00 pm",
          openings: 5,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 3,
          start_time: "9:00 am",
          end_time: "3:00 pm",
          openings: 7,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 4,
          start_time: "10:00 am",
          end_time: "1:00 pm",
          openings: 4,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 5,
          start_time: "9:00 am",
          end_time: "12:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 5,
          start_time: "12:00 pm",
          end_time: "2:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 5,
          start_time: "2:00 pm",
          end_time: "5:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 6,
          start_time: "12:00 pm",
          end_time: "4:00 pm",
          openings: 2,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 6,
          start_time: "12:00 pm",
          end_time: "6:00 pm",
          openings: 2,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 7,
          start_time: "12:00 pm",
          end_time: "4:00 pm",
          openings: 2,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 7,
          start_time: "12:00 pm",
          end_time: "6:00 pm",
          openings: 2,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 8,
          start_time: "12:00 pm",
          end_time: "2:00 pm",
          openings: 8,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 9,
          start_time: "9:00 am",
          end_time: "3:00 pm",
          openings: 8,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 10,
          start_time: "7:00 am",
          end_time: "10:00 am",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 10,
          start_time: "10:00 am",
          end_time: "1:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 10,
          start_time: "1:00 pm",
          end_time: "4:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 11,
          start_time: "9:00 am",
          end_time: "2:00 pm",
          openings: 6,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 12,
          start_time: "9:00 am",
          end_time: "4:00 pm",
          openings: 15,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 13,
          start_time: "9:00 am",
          end_time: "4:00 pm",
          openings: 15,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 14,
          start_time: "10:00 am",
          end_time: "12:00 pm",
          openings: 3,
          applicants: 0,
          status: "open",
        },
        {
          posting_id: 15,
          start_time: "6:00 pm",
          end_time: "8:00 pm",
          openings: 10,
          applicants: 0,
          status: "open",
        },
      ]);
    });
};
